### ISSUE TITLE
Add Support for $count Within $filter

### ISSUE THREAD

**Issue by curtis-babineau** [balena-io-modules/odata-parser#43]
The `$count` flag is not supported for collections described in `$filter` statements.

Based on examples within the [OData 4 specification](http://docs.oasis-open.org/odata/odata/v4.01/csprd05/part2-url-conventions/odata-v4.01-csprd05-part2-url-conventions.html#sec_AddressingtheCountofaCollection), I found the following:
```
> const parser = require('@resin/odata-parser')
> parser.parse(`/Categories?$filter=Products/$count gt 0`)
SyntaxError: Expected "all", "any", or [^:,/,?,#,[,\],@,!,$,*,&,(,),+,,,;,=, ,%] but "$" found.
    at peg$buildStructuredError (/mnt/c/Users/babineac/Documents/GitHub/platform-api-conversations/api-gateway/node_modules/@resin/odata-parser/odata-parser.js:607:12)
    at peg$buildError (/mnt/c/Users/babineac/Documents/GitHub/platform-api-conversations/api-gateway/node_modules/@resin/odata-parser/odata-parser.js:619:12)
    at Object.peg$parse [as parse] (/mnt/c/Users/babineac/Documents/GitHub/platform-api-conversations/api-gateway/node_modules/@resin/odata-parser/odata-parser.js:6157:11)
```

**Comment by Page-** [comment]
Implemented in #44
